services:
  front_end:
    build:
      context: ./front_end
    volumes:
      - ./front_end:/client
    ports:
      - 3001:3001
  back_end:
    build:
      context: ./back_end
    volumes:
      - ./back_end:/app
    ports:
      - 8000:8000
