services:
  redis:
    image: redis:latest
    container_name: redis_broker
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3
    networks:
      - app-network

  worker:
    build: ./
    command: celery -A celery_app.worker.celery worker --loglevel=info --logfile=logs/celery.log
    depends_on:
      redis:
        condition: service_healthy
    
  server:
    build:
      context: ./
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - app-network
    
networks:
  app-network:
    driver: bridge